const CRYPTOPANIC_API_KEY = process.env.CRYPTOPANIC_API_KEY;
const COINMARKET_CAP_API_KEY = process.env.COINMARKET_CAP_API_KEY;

module.exports = {
    CRYPTOPANIC_API_KEY,
    COINMARKET_CAP_API_KEY,
}