# coingecko params
@id=bitcoin
@date=30-12-2023

# binance params
@symbol=BTCUSDT
@interval=15m
@limit=1000


# coingecko.com

###
GET https://api.coingecko.com/api/v3/search/trending

###
GET https://api.coingecko.com/api/v3/coins/{{id}}/market_chart?vs_currency=usd&days=1

###
GET https://api.coingecko.com/api/v3/coins/list

###
GET https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=true

###
GET https://api.coingecko.com/api/v3/coins/{{id}}/history?date={{date}}

###
GET https://api.coingecko.com/api/v3/coins/{{id}}/market_chart?vs_currency=usd&days=100

# binance api
# get account info
###
GET https://api.binance.com/api/v3/klines?symbol={{symbol}}&interval={{interval}}&limit={{limit}}
Content-Type: application/json

###
GET https://api.binance.com/api/v3/ticker/24hr

# coinmarketcap.com

# get trending coins
### not available in free plan
#GET https://pro-api.coinmarketcap.com/v1/cryptocurrency/trending/gainers-losers
#Content-Type: application/json
#X-CMC_PRO_API_KEY:{{COINMARKET_CAP_API_KEY}}



### Not available in free plan
#GET https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest?id=2&convert=USD
#Content-Type: application/json
#X-CMC_PRO_API_KEY:{{COINMARKET_CAP_API_KEY}}



###
# Get historical market data include price, market cap, and 24h volume (granularity auto)
#
#Data granularity is automatic (cannot be adjusted)
#
#1 day from current time = 5 minute interval data
#2 - 90 days from current time = hourly data
#above 90 days from current time = daily data (00:00 UTC)
#Cache based on days range:
#
#1 day = 30 seconds cache
#2-90 days = 30 minutes cache
#90 days = 12 hours cache
#The last completed UTC day (00:00) is available 35 minutes after midnight on the next UTC day (00:35). The cache will always expire at 00:40 UTC.

GET https://api.coingecko.com/api/v3/coins/{{id}}/market_chart?vs_currency=usd&days=10
Content-Type: application/json
X-CMC_PRO_API_KEY:{{COINMARKET_CAP_API_KEY}}


###
# Candle's body - data granularity is automatic (cannot be adjusted for public api users):
#
#1 - 2 days: 30 minutes
#3 - 30 days: 4 hours
#31 days and beyond: 4 days
#Daily candle interval parameter is available for paid plan users only (Analyst/Lite/Pro/Enterprise), use interval=daily parameter in your request:
#
#'daily' interval: available for 1/7/14/30/90/180 days
#Cache / Update Frequency: every 30 minutes
#The last completed UTC day (00:00) is available 35 minutes after midnight on the next UTC day (00:35).

GET https://api.coingecko.com/api/v3/coins/{{id}}/ohlc?vs_currency=usd&days=90
Content-Type: application/json
X-CMC_PRO_API_KEY:{{COINMARKET_CAP_API_KEY}}





