


# coingecko params
@id=bitcoin
@date=30-12-2023

# binance params
@symbol=BTCUSDT
@interval=15m
@limit=1000


# coingecko.com

###
GET https://api.coingecko.com/api/v3/search/trending




###
GET https://api.coingecko.com/api/v3/coins/{{id}}/market_chart?vs_currency=usd&days=1

###
GET https://api.coingecko.com/api/v3/coins/list

###
GET https://api.coingecko.com/api/v3/coins/{{id}}/history?date={{date}}



###
GET https://api.coingecko.com/api/v3/coins/{{id}}/market_chart?vs_currency=usd&days=100





# binance api
# get account info
###
GET https://api.binance.com/api/v3/klines?symbol={{symbol}}&interval={{interval}}&limit={{limit}}
Content-Type: application/json

###
GET https://api.binance.com/api/v3/ticker/24hr



# coinmarketcap.com

# get trending coins
###
GET https://pro-api.coinmarketcap.com/v1/cryptocurrency/trending/gainers-losers
Content-Type: application/json
X-CMC_PRO_API_KEY:{{COINMARKET_CAP_API_KEY}}



###
GET https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest?id=2&convert=USD
Content-Type: application/json
X-CMC_PRO_API_KEY:{{COINMARKET_CAP_API_KEY}}





