###
GET http://localhost:3000/api/v1/hello

###
GET http://localhost:3000/api/v1/wait?delay=2000

###
GET http://localhost:3000/api/v1/topCoins


###
GET http://localhost:3000/api/v1/trending


###
GET http://localhost:3000/api/v1/headlines

###
GET http://localhost:3000/api/v1/headlines?symbol=sol
